---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm install -g tree-sitter-cli
          tree-sitter generate
      - name: Test
        run: |
          tree-sitter test

  deploy-npm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm install -g tree-sitter-cli bun
          tree-sitter init -u
          tree-sitter generate
          bun install --ignore-scripts
          # https://github.com/tree-sitter/tree-sitter/issues/5752
          perl -pi -es/freed-wu/Freed-Wu/ package.json
      - name: Build
        run: |
          npm pack
        env:
          NODE_ENV: production
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.tgz"
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_ENV: production
        run: |
          npm publish

  deploy-cargo:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm install -g tree-sitter-cli
          tree-sitter init -u
          tree-sitter generate
      - name: Build
        run: |
          cargo package
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "target/package/*.crate"
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cargo publish --token ${{secrets.CARGO_TOKEN}}

  deploy-luarocks:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v6
      - name: Install dependencies
        run: |
          luarocks install tree-sitter-cli
      - uses: lumen-oss/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          extra_luarocks_args: |
            --force
          version: scm
          template: tree-sitter-tmux-scm-1.rockspec
      - uses: lumen-oss/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          extra_luarocks_args: |
            --force
          template: tree-sitter-tmux-scm-1.rockspec

  build-wheels:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux'
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm install -g tree-sitter-cli
          tree-sitter init -u
          tree-sitter generate
      - uses: pypa/cibuildwheel@v2.16
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            wheelhouse/*.whl

  build:
    needs:
      - build-wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm install -g tree-sitter-cli
          tree-sitter init -u
          tree-sitter generate
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - name: Build
        run: |
          pip install uv
          uv build --sdist
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          name: artifact-sdist
          path: |
            dist/*
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: dist
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # body_path: build/CHANGELOG.md
          files: |
            dist/*
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
